routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Achievement;
use App\Direction;

//пути для администратора
Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::get('/dashboard/edit', 'DashboardController@edit')->name('admin.dashboard.edit');
    Route::put('/dashboard/update', 'DashboardController@update')->name('admin.dashboard.update');

    Route::resource('/direction', 'DirectionController', ['as'=>'admin']);
    Route::resource('/news', 'NewsController', ['as'=>'admin']);
    Route::resource('/achievements', 'AchievementController', ['as'=>'admin']);
    Route::resource('/feedback', 'FeedbackController', ['as'=>'admin']);
    Route::resource('/review', 'ReviewController', ['as'=>'admin']);
    Route::resource('/groups', 'GroupController', ['as'=>'admin']);

    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/children', 'UserController@getAllChildren', ['as' => 'admin'])->name('admin.children');
});

Route::group(['prefix'=>'auth', 'namespace'=>'Auth', 'middleware'=>['auth']], function(){
    Route::resource('/children', 'ChildController', ['as'=>'auth']);
});

Auth::routes();

// здесь тоже понадобится контроллер, так как будет вытаскидать данные из бд
Route::get('/', function () {
    return view('welcome', [
        'achievements'=> Achievement::all(),
        'directions'=> Direction::all()
    ]);
});

Route::get('/admin/schedule', function () {
    return view('admin.schedule.index');
})->name('admin.schedule');


Route::get('/home', 'HomeController@index')->name('home');


// IndexController возвращает вьюшки для основных страниц
Route::get('/contact', 'IndexController@contact')->name('contact');
Route::get('/news', 'IndexController@news')->name('news');
Route::get('/review', 'IndexController@review')->name('review');

app/Http/Controllers/Admin/ReviewController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Review;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.review.index', [
            // описываем в массиве, какие параметры будем возвращать
            'reviews' => Review::paginate(10)
        ]);
    }

    public function create()
    {

    }

    public function store(Request $request)
    {
        Review::create($request->all());
        return view('review.success');
    }

    public function show(Review $review)
    {

    }

    public function edit(Review $review)
    {
        //
    }

    public function update(Request $request, Review $review)
    {
        $review->published = true;
        $review->save();
        return redirect()->route('admin.review.index');
    }

    public function destroy(Review $review)
    {
        $review->delete();
        return redirect()->route('admin.review.index');
    }
}

resources/views/admin/review/index.blade.php
<!-- Все файлы, не являющиеся частями других файлов, должны наследоваться от этого шаблона -->
@extends('layouts.app')

<!-- А весь контент содержать в блоке "content" -->
@section('content')
    <!-- Вставляем админскую шапку и сайдбар -->
    @include('admin.layouts.sidebar')
    <!-- Основное содержание страницы (соответствует названию файла) -->
    <main class="l-main">
        <div class="content-wrapper">
            <div class="container">
                @component('admin.components.breadcrumbs')
                    @slot('active') Отзывы @endslot
                @endcomponent
                <h3>Отзывы</h3>

                <div id="reviews-list" class="items-list">
                    <div class="items-list-header">
                        <div>Дата</div>
                        <div>Отправитель</div>
                        <div>Текст отзыва</div>
                        <div>Статус</div>
                        <div>Удалить</div>
                    </div>
                    <div class="items-list-body">
                        @forelse($reviews as $review)
                            <div class="items-list-row">
                                <div>{{date('d-m-Y',strtotime($review->created_at))}}</div>
                                <div>{{$review->author->name}}</div>
                                <div>{{$review->text}}</div>
                                <form class="actions" onsubmit="if(confirm('Вы действительно хотите опубликовать отзыв?'))
                                   { return true } else { return false}"
                                      action="{{route('admin.review.update', $review)}}" method="post" enctype="multipart/form-data">
                                    <input type="hidden" name="_method" value="put">
                                    {{ csrf_field() }}
                                    @if($review->published == false)
                                        <button type="submit" title="Опубликовать" class="ordinary-button orange">Опубликовать</button>
                                    @else
                                        <h6 class="published-success"><i class="fas fa-check"></i>Опубликован</h6>
                                    @endif
                                </form>
                                <form class="actions" onsubmit="if(confirm('Вы действительно хотите удалить?'))
                                   { return true } else { return false}"
                                      action="{{route('admin.review.destroy', $review)}}" method="post">
                                    <input type="hidden" name="_method" value="DELETE">
                                    {{ csrf_field() }}
                                    <button type="submit" title="Удалить элемент" class="ordinary-button orange"><i class="far fa-trash-alt"></i></button>
                                </form>
                            </div>
                        @empty
                            <div class="items-list-row">
                                <div> :( </div>
                                <div> :( </div>
                                <div class="mid_text">Данные отсутствуют</div>
                                <div> :( </div>
                            </div>
                        @endforelse
                    </div>
                </div>
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {{$reviews->links()}}
                    </ul>
                </nav>
            </div>
        </div>
    </main>


@endsection