routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Achievement;
use App\Direction;

//пути для администратора
Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::get('/dashboard/edit', 'DashboardController@edit')->name('admin.dashboard.edit');
    Route::put('/dashboard/update', 'DashboardController@update')->name('admin.dashboard.update');

    Route::resource('/direction', 'DirectionController', ['as'=>'admin']);
    Route::resource('/news', 'NewsController', ['as'=>'admin']);
    Route::resource('/achievements', 'AchievementController', ['as'=>'admin']);
    Route::resource('/feedback', 'FeedbackController', ['as'=>'admin']);
    Route::resource('/review', 'ReviewController', ['as'=>'admin']);
    Route::resource('/groups', 'GroupController', ['as'=>'admin']);

    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/children', 'UserController@getAllChildren', ['as' => 'admin'])->name('admin.children');
});

Route::group(['prefix'=>'auth', 'namespace'=>'Auth', 'middleware'=>['auth']], function(){
    Route::resource('/children', 'ChildController', ['as'=>'auth']);
});

Auth::routes();

// здесь тоже понадобится контроллер, так как будет вытаскидать данные из бд
Route::get('/', function () {
    return view('welcome', [
        'achievements'=> Achievement::all(),
        'directions'=> Direction::all()
    ]);
});

Route::get('/admin/schedule', function () {
    return view('admin.schedule.index');
})->name('admin.schedule');


Route::get('/home', 'HomeController@index')->name('home');


// IndexController возвращает вьюшки для основных страниц
Route::get('/contact', 'IndexController@contact')->name('contact');
Route::get('/news', 'IndexController@news')->name('news');
Route::get('/review', 'IndexController@review')->name('review');

app/Feedback.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feedback extends Model
{
    protected $fillable = ['sender', 'message', 'phone', 'email', 'type'];
}

app/Http/Controllers/Admin/FeedbackController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Feedback;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Mail;

class FeedbackController extends Controller
{

    public function index()
    {
        return view('admin.feedback.index', [
            'feedbacks' => Feedback::paginate(10)
        ]);
    }

    public function create()
    {

    }

    public function store(Request $request)
    {
//        $sender = $request->get('sender');
//        $message = $request->get('message');

        // отправка письма на почту логопеду
        Mail::send(['text'=>'admin.mail.mail_form'], ['name', 'Message for logopedist'], function($message){
            $message->to('logopedtomsk@yandex.ru', 'Message to logopedist')->subject('Новое письмо с сайта');
            $message->from('logopedtomsk@yandex.ru','Сайт логопеда');
        });

        Feedback::create($request->all());
        return view('admin.feedback.success');
    }

    public function show(Feedback $feedback)
    {
        return view('admin.feedback.feedback_item', [
            'feedback'   => $feedback
        ]);
    }

    public function edit(Feedback $feedback)
    {
        //
    }

    public function update(Request $request, Feedback $feedback)
    {
        //
    }

    public function destroy(Feedback $feedback)
    {
        $feedback->delete();
        return redirect()->route('admin.feedback.index');
    }
}

resources/views/admin/feedback/feedback_item.blade.php
<!-- Все файлы, не являющиеся частями других файлов, должны наследоваться от этого шаблона -->
@extends('layouts.app')

<!-- А весь контент содержать в блоке "content" -->
@section('content')

    <!-- Вставляем админскую шапку и сайдбар -->
    @include('admin.layouts.sidebar')

    <!-- Основное содержание страницы (соответствует названию файла) -->
    <main class="l-main">
        <div class="content-wrapper">
            <div class="container">
                @component('admin.components.breadcrumbs')
                    @slot('active') Заявки @endslot
                @endcomponent

                @if ($feedback->type === "phone")
                    <div class="main-title"> Заявка на звонок</div>
                @else
                    <div class="main-title"> Вопрос</div>
                @endif
                <form class="info-form">
                    <div class="form-group row">
                      <label class="col-md-2 col-form-label"><i class="far fa-calendar-alt"></i> Дата </label>
                      <div class="col-md-10 col-form-label">{{date('d-m-Y',strtotime($feedback->created_at))}}</div>
                  </div>
                  <div class="form-group row">
                      <label class="col-md-2 col-form-label"><i class="far fa-user"></i> Отправитель </label>
                      <div class="col-md-10 col-form-label">{{$feedback->sender}}</div>
                  </div>
                  <div class="form-group row">
                      <label class="col-md-2 col-form-label"><i class="fas fa-mobile-alt"></i>Телефон: </label>
                      <div class="col-md-10 col-form-label">{{$feedback->phone}}</div>
                  </div>
                    @isset($feedback->email)
                        <div class="form-group row">
                          <label class="col-md-2 col-form-label"><i class="far fa-envelope"></i>E-mail: </label>
                          <div class="col-md-10 col-form-label">{{$feedback->email}}</div>
                      </div>
                    @endisset

                    @isset($feedback->message)
                        <div class="form-group row">
                          <label class="col-md-2 col-form-label"><i class="fas fa-envelope-open-text"></i>Сообщение </label>
                          <div class="col-md-10 col-form-label">{{$feedback->message}}</div>
                      </div>
                    @endisset
                    @if ($feedback->type === "phone")
                        <div class="form-group row">
                            <label class="col-md-12 col-form-label"><i class="far fa-check-circle"></i>
                                Заявка была отправлена через форму "Заказать обратный звонок"
                            </label>
                        </div>
                    @else
                        <div class="form-group row">
                            <label class="col-md-12 col-form-label"><i class="far fa-check-circle"></i>
                                Заявка была отправлена через форму "Задать вопрос"
                            </label>
                        </div>
                    @endif
              </form>
            </div>
        </div>
    </main>
@endsection

resources/views/admin/feedback/index.blade.php
<!-- Все файлы, не являющиеся частями других файлов, должны наследоваться от этого шаблона -->
@extends('layouts.app')

<!-- А весь контент содержать в блоке "content" -->
@section('content')

    <!-- Вставляем админскую шапку и сайдбар -->
    @include('admin.layouts.sidebar')

    <!-- Основное содержание страницы (соответствует названию файла) -->
    <main class="l-main">
        <div class="content-wrapper">
            <div class="container">
                @component('admin.components.breadcrumbs')
                    @slot('active') Заявки @endslot
                @endcomponent
                <h3>Заявки</h3>
                    <div id="" class="items-list">
                        <div class="items-list-header" style="grid-template-columns:1fr 3fr 4fr 1fr;!important;">
                            <div>Дата</div>
                            <div>Отправитель</div>
                            <div>Текст</div>
                            <div>Действие</div>
                        </div>
                        <div class="items-list-body">
                            @forelse($feedbacks as $feedback)
                                <div class="items-list-row"  style="grid-template-columns:1fr 3fr 4fr 1fr;!important;">
                                    <div>{{date('d-m-Y',strtotime($feedback->created_at))}}</div>
                                    <div>
                                        <a href="{{route('admin.feedback.show', $feedback)}}">{{$feedback->sender}}</a>
                                    </div>
                                    <div>{{$feedback->message}}</div>

                                     <form class="actions" onsubmit="if(confirm('Вы действительно хотите удалить?'))
                                       { return true }
                                       else { return false}"
                                               action="{{route('admin.feedback.destroy', $feedback)}}" method="post">
                                            <input type="hidden" name="_method" value="DELETE">
                                             {{ csrf_field() }}
                                             <button type="submit" title="Удалить элемент" class="ordinary-button orange"><i class="far fa-trash-alt"></i></button>
                                    </form>
                                </div>
                            @empty
                                <div class="items-list-row">
                                    <div> :( </div>
                                    <div> :( </div>
                                    <div class="mid_text">Данные отсутствуют</div>
                                    <div> :( </div>
                                </div>
                            @endforelse
                        </div>
                    </div>
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            {{$feedbacks->links()}}
                        </ul>
                    </nav>
            </div>
        </div>
    </main>
@endsection

resources/views/admin/feedback/success.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts/header')

    <div class="container">
        <div class="alert alert-success alert-message d-flex rounded p-0" role="alert">
            <div class="alert-icon d-flex justify-content-center align-items-center flex-grow-0 flex-shrink-0 py-3">
                <i class="fa fa-check"></i>
            </div>
            <div class="d-flex flex-grow-8 align-items-center py-2 pr-1 text">
                Ваша заявка успешно отправлена, ожидайте ответа!
            </div>
        </div>
    </div>

@endsection