routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Achievement;
use App\Direction;

//пути для администратора
Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::get('/dashboard/edit', 'DashboardController@edit')->name('admin.dashboard.edit');
    Route::put('/dashboard/update', 'DashboardController@update')->name('admin.dashboard.update');

    Route::resource('/direction', 'DirectionController', ['as'=>'admin']);
    Route::resource('/news', 'NewsController', ['as'=>'admin']);
    Route::resource('/achievements', 'AchievementController', ['as'=>'admin']);
    Route::resource('/feedback', 'FeedbackController', ['as'=>'admin']);
    Route::resource('/review', 'ReviewController', ['as'=>'admin']);
    Route::resource('/groups', 'GroupController', ['as'=>'admin']);

    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/children', 'UserController@getAllChildren', ['as' => 'admin'])->name('admin.children');
});

Route::group(['prefix'=>'auth', 'namespace'=>'Auth', 'middleware'=>['auth']], function(){
    Route::resource('/children', 'ChildController', ['as'=>'auth']);
});

Auth::routes();

// здесь тоже понадобится контроллер, так как будет вытаскидать данные из бд
Route::get('/', function () {
    return view('welcome', [
        'achievements'=> Achievement::all(),
        'directions'=> Direction::all()
    ]);
});

Route::get('/admin/schedule', function () {
    return view('admin.schedule.index');
})->name('admin.schedule');


Route::get('/home', 'HomeController@index')->name('home');


// IndexController возвращает вьюшки для основных страниц
Route::get('/contact', 'IndexController@contact')->name('contact');
Route::get('/news', 'IndexController@news')->name('news');
Route::get('/review', 'IndexController@review')->name('review');

app/Achievement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Achievement extends Model
{
    protected $fillable = ['image', 'description'];
}

app/Http/Controllers/Admin/AchievementController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Achievement;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Input;


class AchievementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.achievements.index', [
            'achievements' => Achievement::orderBy('id', 'desc')->paginate(5),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.achievements.create', [
            'achievement'=> new Achievement()
//            'directions' => Direction::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $file = Input::file('image');

        if ($file) {
            $image = Image::make(Input::file('image'));
            $path = storage_path().'/app/public/achievements/';
            $time = time();

            $image->save($path.$time.'.'.$file->getClientOriginalName());
            $image->resize(50, null, function ($constraint) {
                $constraint->aspectRatio();
            });
            $image->save($path.'previews/'.$time.'.'.$file->getClientOriginalName());
        }

        $achievement = Achievement::create($request->all());

        if ($file) {
            $achievement->image = $time.'.'.$file->getClientOriginalName();
        }

        $achievement->save();

        return redirect()->route('admin.achievements.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Achievement  $achievments
     * @return \Illuminate\Http\Response
     */
    public function show(Achievement $achievments)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Achievement  $achievement
     * @return \Illuminate\Http\Response
     */
    public function edit(Achievement $achievement)
    {
        return view('admin.achievements.edit', [
            'achievement' => $achievement
//            'directions' => Direction::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Achievement  $achievment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Achievement $achievement)
    {
        $file = Input::file('image');
        if ($file) {
            $image = Image::make(Input::file('image'));
            $path = storage_path().'/app/public/achievements/';
            $time = time();

            $image->save($path.$time.'.'.$file->getClientOriginalName());
            $image->resize(50, null, function ($constraint) {
                $constraint->aspectRatio();
            });
            $image->save($path.'previews/'.$time.'.'.$file->getClientOriginalName());
        }

        $achievement->update($request->all());
        if ($file) {
            $achievement->image = $time.'.'.$file->getClientOriginalName();
        }

        $achievement->save();


        return redirect()->route('admin.achievements.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Achievement  $achievement
     * @return \Illuminate\Http\Response
     */
    public function destroy(Achievement $achievement)
    {
        $achievement->delete();
        return redirect()->route('admin.achievements.index');
    }
}

resources/views/admin/achievements/create.blade.php
<!-- Все файлы, не являющиеся частями других файлов, должны наследоваться от этого шаблона -->
@extends('layouts.app')

<!-- А весь контент содержать в блоке "content" -->
@section('content')

    <!-- Вставляем админскую шапку и сайдбар -->
    @include('admin.layouts.sidebar')

    <!-- Основное содержание страницы (соответствует названию файла) -->
    <main class="l-main">
        <div class="content-wrapper">
            <div class="container">
                @component('admin.components.breadcrumbs')
                    @slot('active') Достижения @endslot
                @endcomponent

                <div class="large_text">Добавление нового достижения</div>
                <form class="form-horizontal" action="{{route('admin.achievements.store')}}" method="post" enctype="multipart/form-data">
                    {{--передаем токен в форме через хелпер--}}
                    {{ csrf_field() }}

                    {{--Form Include--}}
                    @include('admin.achievements.form', ['image_required' => ''])
                </form>
            </div>
        </div>
    </main>
@endsection

resources/views/admin/achievements/edit.blade.php
<!-- Все файлы, не являющиеся частями других файлов, должны наследоваться от этого шаблона -->
@extends('layouts.app')

<!-- А весь контент содержать в блоке "content" -->
@section('content')

    <!-- Вставляем админскую шапку и сайдбар -->
    @include('admin.layouts.sidebar')

    <!-- Основное содержание страницы (соответствует названию файла) -->
    <main class="l-main">
        <div class="content-wrapper">
            <div class="container">
                @component('admin.components.breadcrumbs')
                    @slot('active') Направления @endslot
                @endcomponent

                <div class="large_text">Редактирование достижения</div>
                <form class="form-horizontal" action="{{route('admin.achievements.update', $achievement)}}"
                      method="post" enctype="multipart/form-data">
                    <input type="hidden" name="_method" value="put">
                    {{--передаем токен в форме через хелпер--}}
                    {{ csrf_field() }}

                    {{--Form Include--}}
                    @include('admin.achievements.form', ['achievement' => $achievement, 'image-required' => ''])
                </form>
            </div>
        </div>
    </main>

@endsection

resources/views/admin/achievements/form.blade.php
{{--форма для создания и обновления--}}

<div class="form-group">
    <label for="description">Описание</label>
    <textarea id="description" type="text" class="form-control" name="description"
              placeholder="Описание достижения" required>
            {{$achievement->description ?? ""}}
        </textarea>
</div>
<div class="form-group">
    <label for="image">Изображение</label>
    <input id="image" type="file" name="image" value="{{$achievement->image ?? ""}}" {{$image_required ?? ""}}>
</div>
{{--Вывод картинки--}}
@if($achievement->image)
    <img src="{{asset('/storage/achievements/' . $achievement->image)}}" alt="{{$achievement->image ?? ""}}">
@endif

<div class="d-flex justify-content-end">
    <a href="{{route('admin.achievements.index')}}" class="ordinary-button grey" type="button" style="margin-right: 10px"> Отменить</a>
    <button class="ordinary-button orange" type="submit">Сохранить</button>
</div>

resources/views/admin/achievements/index.blade.php
<!-- Все файлы, не являющиеся частями других файлов, должны наследоваться от этого шаблона -->
@extends('layouts.app')

<!-- А весь контент содержать в блоке "content" -->
@section('content')

    <!-- Вставляем админскую шапку и сайдбар -->
    @include('admin.layouts.sidebar')

    <!-- Основное содержание страницы (соответствует названию файла) -->
    <main class="l-main">
        <div class="content-wrapper">
            <div class="container">
                @component('admin.components.breadcrumbs')
                    @slot('active') Достижения @endslot
                @endcomponent

                <h3>Список достижений</h3>
                <div class="d-flex justify-content-end">
                    <a href="{{route('admin.achievements.create')}}" class="ordinary-button orange">
                    Добавить<i class="far fa-plus-square"></i></a>
                </div>
                <div id="achievements-list" class="items-list">
                    <div class="items-list-header">
                        <div>Картинка</div>
                        <div>Описание</div>
                        <div>Действия</div>
                    </div>
                    <div class="items-list-body">
                        @forelse($achievements as $achievement)
                            <div class="items-list-row">
                                <div>
                                    <img style="width: 50px;" src="{{asset('/storage/achievements/previews/' . $achievement->image)}}" alt="{{$achievement->image ?? ""}}">
                                </div>
                                <div>{{$achievement->description}}</div>
                                <form class="actions" onsubmit="if(confirm('Вы действительно хотите удалить?'))
                                   { return true }
                                   else { return false}"
                                      action="{{route('admin.achievements.destroy', $achievement)}}" method="post">
                                        <input type="hidden" name="_method" value="DELETE">
                                    {{ csrf_field() }}

                                    <a title="Изменить элемент" href="{{route('admin.achievements.edit', $achievement)}}" class="ordinary-button green"><i class="far fa-edit"></i></a>
                                        <button type="submit" title="Удалить элемент" class="ordinary-button orange"><i class="far fa-trash-alt"></i></button>
                                </form>
                            </div>
                        @empty
                            <div class="items-list-row">
                                <div> :( </div>
                                <div class="mid_text">Данные отсутствуют</div>
                                <div> :( </div>
                            </div>
                        @endforelse
                    </div>
                </div>
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {{$achievements->links()}}
                    </ul>
                </nav>
            </div>
        </div>
    </main>

@endsection