routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Achievement;
use App\Direction;

//пути для администратора
Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::get('/dashboard/edit', 'DashboardController@edit')->name('admin.dashboard.edit');
    Route::put('/dashboard/update', 'DashboardController@update')->name('admin.dashboard.update');

    Route::resource('/direction', 'DirectionController', ['as'=>'admin']);
    Route::resource('/news', 'NewsController', ['as'=>'admin']);
    Route::resource('/achievements', 'AchievementController', ['as'=>'admin']);
    Route::resource('/feedback', 'FeedbackController', ['as'=>'admin']);
    Route::resource('/review', 'ReviewController', ['as'=>'admin']);
    Route::resource('/groups', 'GroupController', ['as'=>'admin']);

    Route::resource('/user', 'UserController', ['as' => 'admin']);
    Route::get('/children', 'UserController@getAllChildren', ['as' => 'admin'])->name('admin.children');
});

Route::group(['prefix'=>'auth', 'namespace'=>'Auth', 'middleware'=>['auth']], function(){
    Route::resource('/children', 'ChildController', ['as'=>'auth']);
});

Auth::routes();

// здесь тоже понадобится контроллер, так как будет вытаскидать данные из бд
Route::get('/', function () {
    return view('welcome', [
        'achievements'=> Achievement::all(),
        'directions'=> Direction::all()
    ]);
});

Route::get('/admin/schedule', function () {
    return view('admin.schedule.index');
})->name('admin.schedule');


Route::get('/home', 'HomeController@index')->name('home');


// IndexController возвращает вьюшки для основных страниц
Route::get('/contact', 'IndexController@contact')->name('contact');
Route::get('/news', 'IndexController@news')->name('news');
Route::get('/review', 'IndexController@review')->name('review');

app/Direction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Direction extends Model
{
    protected $fillable = ['title', 'description', 'image'];
}

app/Http/Controllers/Admin/DirectionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Direction;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Input;

class DirectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //вернем список
        return view('admin.direction.index', [
            // описываем в массиве, какие параметры будем возвращать
            'directions' => Direction::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.direction.create', [
            'direction'=> new Direction(),
            'directions' => Direction::all() ///
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $file = Input::file('image');

        if ($file) {
            $image = Image::make(Input::file('image'));
            $path = storage_path().'/app/public/directions/';
            $time = time();

            $image->save($path.$time.'.'.$file->getClientOriginalName());
            $image->resize(50, null, function ($constraint) {
                $constraint->aspectRatio();
            });
            $image->save($path.'previews/'.$time.'.'.$file->getClientOriginalName());
        }


        $direction = Direction::create($request->all());

        if ($file) {
            $direction->image = $time.'.'.$file->getClientOriginalName();
        }

        $direction->save();

        return redirect()->route('admin.direction.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Direction  $direction
     * @return \Illuminate\Http\Response
     */
    public function show(Direction $direction)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Direction  $direction
     * @return \Illuminate\Http\Response
     */
    public function edit(Direction $direction)
    {
        return view('admin.direction.edit', [
            'direction'   => $direction,
            'directions' => Direction::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Direction  $direction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Direction $direction)
    {
        $file = Input::file('image');
        if ($file) {
            $image = Image::make(Input::file('image'));
            $path = storage_path().'/app/public/directions/';
            $time = time();

            $image->save($path.$time.'.'.$file->getClientOriginalName());
            $image->resize(50, null, function ($constraint) {
                $constraint->aspectRatio();
            });
            $image->save($path.'previews/'.$time.'.'.$file->getClientOriginalName());
        }

        $direction->update($request->all());
        if ($file) {
            $direction->image = $time.'.'.$file->getClientOriginalName();
        }

        $direction->save();

        return redirect()->route('admin.direction.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Direction  $direction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Direction $direction)
    {
        $direction->delete();
        return redirect()->route('admin.direction.index');
    }

    public function imageLoad(Request $request){

    }
}

resources/views/admin/direction/create.blade.php
<!-- Все файлы, не являющиеся частями других файлов, должны наследоваться от этого шаблона -->
@extends('layouts.app')

<!-- А весь контент содержать в блоке "content" -->
@section('content')

    <!-- Вставляем админскую шапку и сайдбар -->
    @include('admin.layouts.sidebar')

    <!-- Основное содержание страницы (соответствует названию файла) -->
    <main class="l-main">
        <div class="content-wrapper">
            <div class="container">
                @component('admin.components.breadcrumbs')
                    @slot('active') Направления работы @endslot
                @endcomponent

                <div class="large_text">Добавление нового направления</div>
                <form class="form-horizontal" action="{{route('admin.direction.store')}}"
                      method="post" enctype="multipart/form-data">
                    {{--передаем токен в форме через хелпер--}}
                    {{ csrf_field() }}

                    {{--Form Include--}}
                    @include('admin.direction.form', ['image_required' => ''])
                </form>
            </div>
        </div>
    </main>
@endsection

resources/views/admin/direction/edit.blade.php
<!-- Все файлы, не являющиеся частями других файлов, должны наследоваться от этого шаблона -->
@extends('layouts.app')

<!-- А весь контент содержать в блоке "content" -->
@section('content')

    <!-- Вставляем админскую шапку и сайдбар -->
    @include('admin.layouts.sidebar')

    <!-- Основное содержание страницы (соответствует названию файла) -->
    <main class="l-main">
        <div class="content-wrapper">
            <div class="container">
                @component('admin.components.breadcrumbs')
                    @slot('active') Направления @endslot
                @endcomponent

                <div class="large_text">Редактирование направления</div>
                <form class="form-horizontal" action="{{route('admin.direction.update', $direction)}}"
                      method="post" enctype="multipart/form-data">
                    <input type="hidden" name="_method" value="put">
                    {{--передаем токен в форме через хелпер--}}
                    {{ csrf_field() }}

                    {{--Form Include--}}
                    @include('admin.direction.form',  ['direction' => $direction, 'image-required' => ''])
                </form>
            </div>
        </div>
    </main>

@endsection

resources/views/admin/direction/form.blade.php
{{--форма для создания и обновления--}}
<div class="form-group">
    <label for="title">Заголовок</label>
    <input id="title" type="text" class="form-control" name="title"
           placeholder="Заголовок категории" value="{{$direction->title ?? ''}}" required>
</div>
<div class="form-group">
    <label for="description">Описание</label>
    <textarea id="description" type="text" class="form-control" name="description" placeholder="Описание достижения" required>
            {{$direction->description ?? ""}}
    </textarea>
</div>
<div class="form-group">
    <label for="image">Изображение</label>
    <input id="image" type="file" name="image" value="{{$direction->image ?? ""}}" {{$image_required ?? ""}}>
</div>
{{--Вывод картинки--}}
@if($direction->image)
    <img src="{{asset('/storage/directions/' . $direction->image)}}" alt="{{$direction->image ?? ""}}">
@endif

<div class="d-flex justify-content-end">
    <a href="{{route('admin.direction.index')}}" class="ordinary-button grey" type="button" style="margin-right: 10px"> Отменить</a>
    <button class="ordinary-button orange" type="submit">Сохранить</button>
</div>

    {{--<div class="col-lg-6">--}}
        {{--<label for="">Заголовок</label>--}}
        {{--<input type="text" class="form-control" name="title"--}}
               {{--placeholder="Заголовок категории" value="{{$direction->title ?? ''}}" required>--}}

        {{--<label for="">Описание</label>--}}
        {{--<textarea type="text" class="form-control" name="description"--}}
               {{--placeholder="Заголовок категории" required>--}}
            {{--{{$direction->description ?? ''}}--}}
        {{--</textarea>--}}

        {{--<label for="">Изображение</label>--}}
        {{--<input type="file" name="image" value="{{$direction->image ?? ""}}" style="display: block">--}}

        {{--<a href="{{route('admin.description.index')}}" class="btn" type="button"> Отменить</a>--}}
        {{--<input class="btn btn-primary" type="submit" value="Сохранить" style="margin-top: 20px;">--}}
    {{--</div>--}}

resources/views/admin/direction/index.blade.php
<!-- Все файлы, не являющиеся частями других файлов, должны наследоваться от этого шаблона -->
@extends('layouts.app')

<!-- А весь контент содержать в блоке "content" -->
@section('content')

    <!-- Вставляем админскую шапку и сайдбар -->
    @include('admin.layouts.sidebar')

    <!-- Основное содержание страницы (соответствует названию файла) -->
    <main class="l-main">
        <div class="content-wrapper">
            <div class="container">
                @component('admin.components.breadcrumbs')
                    @slot('active') Направления работы @endslot
                @endcomponent

                <h3>Направления работы</h3>
                <div class="d-flex justify-content-end">
                    <a href="{{route('admin.direction.create')}}" class="ordinary-button orange">
                        Добавить<i class="far fa-plus-square"></i></a>
                </div>
                    <div id="directions-list" class="items-list">
                        <div class="items-list-header">
                            <div>Картинка</div>
                            <div>Заголовок</div>
                            <div>Описание</div>
                            <div>Действия</div>
                        </div>
                        <div class="items-list-body">
                            @forelse($directions as $direction)
                                <div class="items-list-row">
                                    <div>
                                        <img style="width: 50px;" src="{{asset('/storage/directions/previews/' . $direction->image)}}" alt="{{$direction->image ?? ""}}">
                                    </div>
                                    <div>{{$direction->title}}</div>
                                    <div>{{$direction->description}}</div>
                                    <form class="actions" onsubmit="if(confirm('Вы действительно хотите удалить?'))
                                   { return true }
                                   else { return false}"
                                          action="{{route('admin.direction.destroy', $direction)}}" method="post">
                                        <input type="hidden" name="_method" value="DELETE">
                                        {{ csrf_field() }}

                                        <a title="Изменить элемент" href="{{route('admin.direction.edit', $direction)}}" class="ordinary-button green"><i class="far fa-edit"></i></a>
                                        <button type="submit" title="Удалить элемент" class="ordinary-button orange"><i class="far fa-trash-alt"></i></button>
                                    </form>
                                </div>
                            @empty
                                <div class="items-list-row">
                                    <div> :( </div>
                                    <div> :( </div>
                                    <div class="mid_text">Данные отсутствуют</div>
                                    <div> :( </div>
                                </div>
                            @endforelse
                        </div>
                    </div>
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            {{$directions->links()}}
                        </ul>
                    </nav>

                  {{--<table class="table table-striped">--}}
                    {{--<tbody>--}}
                        {{--@forelse($directions as $direction)--}}
                            {{--<tr>--}}
                                {{--обращение к коллекции, а не к массиву, поэтому без квадрат скобок--}}
                                {{--<td>{{$direction->title}}</td>--}}
                                {{--<td>{{$direction->description}}</td>--}}
                                {{--<td class="text-right">--}}
                                    {{--<form onsubmit="if(confirm('Удалить?')){return true} else {return false}"--}}
                                          {{--action="{{route('admin.direction.destroy', ['id'=>$direction])}}" method="post">--}}
                                        {{--<input type="hidden" name="_method" value="DELETE">--}}
                                        {{--{{ csrf_field() }}--}}
                                        {{--<a class="btn btn-default" href="{{route('admin.direction.edit', $direction)}}"> <i class="fa fa-edit"></i></a>--}}
                                        {{--<button type="submit" class="btn"><i class="far fa-trash-alt"></i></button>--}}
                                    {{--</form>--}}
                                {{--</td>--}}
                            {{--</tr>--}}
                        {{--@empty--}}
                            {{--<tr>--}}
                                {{--<td colspan="3" class="text-center">--}}
                                    {{--<h2>Данные отсутствуют</h2>--}}
                                {{--</td>--}}
                            {{--</tr>--}}
                        {{--@endforelse--}}
                    {{--</tbody>--}}
                    {{--<tfoot>--}}
                        {{--<tr>--}}
                            {{--<td colspan="4">--}}
                                {{--<ul class="pagination pull-right">--}}
                                    {{--отрисовка постраничного перехода--}}
                                    {{--links - тоже хелпер--}}
                                    {{--{{$directions->links()}}--}}
                                {{--</ul>--}}
                            {{--</td>--}}
                        {{--</tr>--}}
                    {{--</tfoot>--}}
                {{--</table>--}}
            </div>
        </div>
    </main>
@endsection